server:
  port: 9191
  domain: "localhost"
  timeout: 10s
database:
  type: in-memory
  connection_string: "user:password@tcp(dbserver:3306)/mydatabase"
log:
  level: 0
  path: "E:/log"
cache:
  type: redis
  address: "localhost:6379"
  password:
  username:
  path:
  db:
